import type { CommunityPost, CommunityReply } from './types'

export const previewPosts: CommunityPost[] = [
  {
    id: 'welcome-useful-unit-talk',
    title: 'Read first: useful unit talk without spot-burning',
    body: 'The best planning conversations explain patterns, tradeoffs, and public information without publishing somebody else’s exact camp, access route, glassing point, or private arrangement. Unit-level context is welcome. Coordinates and sensitive locations are not.',
    category: 'campfire',
    postType: 'discussion',
    state: null,
    species: null,
    huntNumber: null,
    authorName: 'Hunt Planner Team',
    isStaff: true,
    createdAt: '2026-07-20T14:15:00.000Z',
    updatedAt: '2026-07-20T14:15:00.000Z',
    lastActivityAt: '2026-07-23T13:30:00.000Z',
    score: 34,
    replyCount: 1,
    viewCount: 312,
    isPinned: true,
    isLocked: false,
    viewerVote: false,
  },
  {
    id: 'db1001-tag-wait',
    title: 'DB1001: how do you weigh a 29-permit tag against the wait?',
    body: 'I’m trying to separate tag quality from name recognition. Hunt Planner shows 29 permits for the 2026 Paunsaugunt archery hunt and a 55.9% reported 2024 harvest rate, but hunters also averaged 9.6 days afield. For similarly scarce early archery hunts, what made the wait worth it: season length, scouting access, buck quality, or something else? Looking for planning principles, not locations.',
    category: 'draws',
    postType: 'question',
    state: 'UT',
    species: 'Deer',
    huntNumber: 'DB1001',
    authorName: 'Wasatch Glass',
    isStaff: true,
    createdAt: '2026-07-22T16:40:00.000Z',
    updatedAt: '2026-07-22T16:40:00.000Z',
    lastActivityAt: '2026-07-23T15:42:00.000Z',
    score: 18,
    replyCount: 3,
    viewCount: 184,
    isPinned: false,
    isLocked: false,
    viewerVote: false,
  },
  {
    id: 'colorado-first-rifle-priorities',
    title: 'Colorado first-rifle elk: harvest success or public-land percentage first?',
    body: 'I have three units in the same general draw range. One leads on recent harvest, another has much more public ground, and the third fits my scouting schedule. How are you weighting those signals before you dig into access and terrain?',
    category: 'planning',
    postType: 'discussion',
    state: 'CO',
    species: 'Elk',
    huntNumber: null,
    authorName: 'Front Range Notes',
    isStaff: true,
    createdAt: '2026-07-21T12:10:00.000Z',
    updatedAt: '2026-07-21T12:10:00.000Z',
    lastActivityAt: '2026-07-23T14:18:00.000Z',
    score: 12,
    replyCount: 0,
    viewCount: 226,
    isPinned: false,
    isLocked: false,
    viewerVote: false,
  },
  {
    id: 'wyoming-pronghorn-access',
    title: 'Wyoming pronghorn: evaluating access without asking for someone’s spot',
    body: 'What public information do you use to separate a unit that merely has public acres from one where those acres are realistically reachable during the season? I’m comparing road layers, land ownership, and agency notes so far.',
    category: 'planning',
    postType: 'question',
    state: 'WY',
    species: 'Pronghorn',
    huntNumber: null,
    authorName: 'Sage Basin',
    isStaff: true,
    createdAt: '2026-07-20T18:05:00.000Z',
    updatedAt: '2026-07-20T18:05:00.000Z',
    lastActivityAt: '2026-07-23T11:22:00.000Z',
    score: 21,
    replyCount: 0,
    viewCount: 401,
    isPinned: false,
    isLocked: false,
    viewerVote: false,
  },
  {
    id: 'first-archery-lessons',
    title: 'Five things I would change after my first western archery hunt',
    body: 'The short version: fewer “just in case” items, more time learning one small area, a better midday water plan, a deliberate pack-out route, and more shooting after a hard uphill effort. Here is what each lesson changed in my next plan.',
    category: 'reports',
    postType: 'hunt-report',
    state: 'ID',
    species: 'Elk',
    huntNumber: null,
    authorName: 'Timberline Rookie',
    isStaff: true,
    createdAt: '2026-07-19T20:25:00.000Z',
    updatedAt: '2026-07-19T20:25:00.000Z',
    lastActivityAt: '2026-07-22T21:06:00.000Z',
    score: 29,
    replyCount: 0,
    viewCount: 566,
    isPinned: false,
    isLocked: false,
    viewerVote: false,
  },
  {
    id: 'tripod-weight-stability',
    title: 'Tripod weight versus stability for an eight-day backpack hunt',
    body: 'For a 65 mm spotter, where did you land after actually carrying the system for a week? I care more about quick setup and wind performance than shaving the last few ounces.',
    category: 'gear',
    postType: 'gear-review',
    state: null,
    species: null,
    huntNumber: null,
    authorName: 'Ridgeline Kit',
    isStaff: true,
    createdAt: '2026-07-21T09:30:00.000Z',
    updatedAt: '2026-07-21T09:30:00.000Z',
    lastActivityAt: '2026-07-22T18:54:00.000Z',
    score: 9,
    replyCount: 0,
    viewCount: 173,
    isPinned: false,
    isLocked: false,
    viewerVote: false,
  },
  {
    id: 'compare-two-hunts',
    title: 'Feature request: compare two hunts side by side',
    body: 'I keep opening two tabs to compare draw outlook, season dates, harvest success, and public land. A pinned comparison tray would make the decision much easier. Which four or five fields should always stay visible?',
    category: 'feedback',
    postType: 'site-feedback',
    state: null,
    species: null,
    huntNumber: null,
    authorName: 'Two Tab Hunter',
    isStaff: true,
    createdAt: '2026-07-22T11:45:00.000Z',
    updatedAt: '2026-07-22T11:45:00.000Z',
    lastActivityAt: '2026-07-22T16:12:00.000Z',
    score: 16,
    replyCount: 0,
    viewCount: 148,
    isPinned: false,
    isLocked: false,
    viewerVote: false,
  },
]

export const previewReplies: Record<string, CommunityReply[]> = {
  'welcome-useful-unit-talk': [
    {
      id: 'welcome-reply-1',
      postId: 'welcome-useful-unit-talk',
      body: 'A good rule of thumb: share how you evaluated access, not the exact access point you chose.',
      authorName: 'Hunt Planner Team',
      createdAt: '2026-07-21T15:30:00.000Z',
      updatedAt: '2026-07-21T15:30:00.000Z',
      helpfulCount: 12,
      isStaff: true,
    },
  ],
  'db1001-tag-wait': [
    {
      id: 'db1001-reply-1',
      postId: 'db1001-tag-wait',
      body: 'For me, available scouting days matter more than the headline success rate. Nine-plus days afield is a useful warning that the tag still asks for real time.',
      authorName: 'Pine Valley',
      createdAt: '2026-07-22T18:15:00.000Z',
      updatedAt: '2026-07-22T18:15:00.000Z',
      helpfulCount: 8,
      isStaff: false,
    },
    {
      id: 'db1001-reply-2',
      postId: 'db1001-tag-wait',
      body: 'Compare it with a hunt you could draw repeatedly. The opportunity cost becomes much clearer when both are in the same planner.',
      authorName: 'Draw Ledger',
      createdAt: '2026-07-23T02:05:00.000Z',
      updatedAt: '2026-07-23T02:05:00.000Z',
      helpfulCount: 6,
      isStaff: false,
    },
    {
      id: 'db1001-reply-3',
      postId: 'db1001-tag-wait',
      body: 'Staff note: always check the current UDWR guidebook and hunt page before applying. The figures discussed here are historical planning context, not a guarantee.',
      authorName: 'Hunt Planner Team',
      createdAt: '2026-07-23T15:42:00.000Z',
      updatedAt: '2026-07-23T15:42:00.000Z',
      helpfulCount: 10,
      isStaff: true,
    },
  ],
}
